FROM docker.io/library/archlinux:latest

RUN pacman -Syu --noconfirm --needed \
        base-devel \
        curl \
        fd \
        fzf \
        git \
        neovim \
        ripgrep \
        tar \
        tree-sitter-cli \
    && rm -rf /var/cache/pacman/pkg/* \
    && install -d -m 0777 /home/sb/.cache

COPY nvim /home/sb/.config/nvim

ENV HOME=/home/sb
ENV PATH="/home/sb/.local/bin:${PATH}"
ENV GIT_CONFIG_GLOBAL=/home/sb/.local/gitconfig
